name: "cmi mqtt"
description: "cmi mqtt data"
version: "1.0.10"
slug: "cmi-mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  cmi_host: ""
  cmi_user: ""
  cmi_password: ""
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  cmi_host: str
  cmi_user: str
  cmi_password: str
